stages:
- build  

build_job:
  stage: build
  only:
  - branches
  script:
  - 'D:\PMY_C\nuget\nuget.exe restore'
  - 'cmd /c "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe" pmy.sln'
  artifacts:
    paths:
    - pmy/bin/Debug/pmy.exe